language: ruby
rvm:
  - "2.4"
  - "2.5"
  - "2.6"
  - "2.7"
  - jruby-9.2.8.0
  - jruby-9.1.17.0
  - truffleruby

before_script:
  - "curl -H 'Cache-Control: no-cache' https://raw.githubusercontent.com/fossas/fossa-cli/master/install.sh | sudo bash"

script:
  - rake
  - fossa init
  - fossa analyze
